# Generated by Django 5.0.7 on 2024-07-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
